behaviors:
  BoatAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 16384
      learning_rate: 1e-4
      beta: 1e-3
      epsilon: 0.2
      lambd: 0.92
      num_epoch: 7
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 224
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    max_steps: 5000000
    time_horizon: 512
    summary_freq: 10000