behaviors:
  BoatAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 1e-4
      beta: 5e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      gail:
        strength: 0.1
        gamma: 0.8
        demo_path: Demos/CollAvoidance.demo
    behavioral_cloning:
      strength: 0.1
      gamma: 0.8
      demo_path: Demos/CollAvoidance.demo
    max_steps: 6e6
    time_horizon: 450
    summary_freq: 10000
